#!/bin/bash

esc=$(printf '\033')

http() {
    echo -ne "s_\\(HTTP/1.1\\) \\($1\\) \\(.*\\)\$_\\1 ${esc}$2\\2${esc}[0m ${esc}$3\\3${esc}[0m_"
}

_prep="s_< _${esc}[1;37m&${esc}[0m_"
_XXX="$(http '[0-9]\{3,3\}'  '[1;34m'    '[34m')"
_2XX="$(http '2[0-9]\{2,2\}' '[1;32m'    '[32m')"
_4XX="$(http '4[0-9]\{2,2\}' '[1;31m'    '[31m')"
_5XX="$(http '5[0-9]\{2,2\}' '[1;37;41m' '[31m')"

res="$(/usr/bin/curl "$@" 2> >(sed -e "$_prep" -e "$_2XX" -e "$_4XX" -e "$_5XX" -e "$_XXX" >&2))"
echo "$res"


# vim: tw=0
