#!/bin/sh

VIM="vim -c :startinsert"

DIARY="$HOME/.diary"
if [ ! -d "$DIARY" ] ; then
    mkdir "$DIARY" || exit 1
fi

if [ ! -f "$DIARY/newfile" ] ; then
    vim -x "$DIARY/newfile"
fi 

DATE="${1:-$(date +%F)}"
FILENAME="$DIARY/$DATE.md"

if [ ! -f "$FILENAME" ] ; then
    vim -c ":silent :saveas $FILENAME" -c :startinsert "$DIARY/newfile"
else 
    vim -c :startinsert "$FILENAME"
fi 
