#!/bin/bash

exclusions=('\.git' 'vendor' 'test' 'models/' 'operations/' '// '
    '\.bash_.*history' '\.stack-work/' 'dist/')

args=()
for e in "${exclusions[@]}"; do
    args+=('-e' "$e")
done

grep -v "$@" "${args[@]}"
