#!/bin/bash

set -euo pipefail

target="$1"
shift

IFS=$'\n'
pods=($(kubectl "$@" get pods -l app="$target" -o json | jq -r '.items | map(.metadata.name) | .[]'))

[ "${#pods[*]}" -gt 0 ]

invoq="tmux -f /dev/null new-session 'kubectl $@ logs --follow ${pods[0]} | jq-maybe'"

unset 'pods[0]'
for pod in "${pods[@]}" ; do
    invoq+=" \\; split-window -h 'kubectl $@ logs --follow $pod | jq-maybe'"
done

invoq+="  \\; select-layout even-horizontal"

set -x
eval $invoq

# vim: tw=0
