#!/bin/sh

set -xue

port="$1"
shift

# nc --allow ::1 -k -l 1080 -c 'timeout 0.25s'
nc --allow ::1 -v -C -k -l $port -c 'env >&2; timeout 0.5s cat -An >&2; echo -e "HTTP/1.1 200 OK\n\n $(date)"; echo -e "\n\e[1;32m...\e[0m" >&2'
# nc --allow 127.0.0.1 -v -C --ssl -k -l $port -c http.hs "$@"
