#!/bin/bash
CONTS="$(xwininfo)"
# X=$(echo "$CONTS" | grep 'Absolute upper-left X' | awk '{print $4}')
X=$(echo "$CONTS" | awk '/Absolute upper-left X/ {print $4}') 
Y=$(echo "$CONTS" | awk '/Absolute upper-left Y/ {print $4}') 
WIDTH=$(( $(echo "$CONTS" | awk '/Width/ {print $2}') / 2 * 2))
HEIGHT=$(( $(echo "$CONTS" | awk '/Height/ {print $2}') / 2 * 2))
FILENAME="Screen $(date +%F\ %T)".mkv
echo "$FILENAME" ${X},${Y} ${WIDTH}x${HEIGHT}
# line1="-y -thread_queue_size 512 -threads 1 -f alsa -ac 2 -i default \
#     -f x11grab -framerate 60 -video_size ${WIDTH},${HEIGHT}                 \
#     -i :0.0+${X},${Y} -vaapi_device /dev/dri/renderD129 -c:v h264_vaapi     \
#     -vf format='nv12,hwupload,fps=60' -preset ultrafast -g 120              \
#     _\"$FILENAME\""
# echo "$line1"
# ffmpeg $line1

ffmpeg -hide_banner -y -thread_queue_size 512 -threads 1                       \
    -loglevel repeat+level+verbose \
    -f pulse -ac 2 -i default                                                  \
    -f x11grab -framerate 60 -video_size ${WIDTH},${HEIGHT}                    \
    -i $DISPLAY.0+${X},${Y} -c:v h264 -g 120 -preset ultrafast                 \
    _"$FILENAME"                                                               \
    &&
    ffmpeg -y -thread_queue_size 512 -i _"$FILENAME" -c:a copy -c:v libx264    \
        -maxrate 6M -bufsize 90M -crf 20 -preset slow -profile:v high10        \
        -pix_fmt yuv420p "$FILENAME"

[[ -w _"$FILENAME" ]] && rm _"$FILENAME"
