#!/bin/bash

colors=('48;5;235' '48;5;237')
# colors=('48;5;18' '48;5;17')

k=${1:-1}

i=0
while read line ; do
    echo -en "\e[${colors[$i]}m"
    printf "%-*s" "$(( $(tput cols) / $k ))" "$line"
    echo -e "\e[0m"
    i=$((($i + 1) % ${#colors[@]}))
done

