#!/bin/bash

sofiles=(
    # /usr/lib/ksm_preload/libksm_preload.so
    # /usr/local/share/ksm_preload/libksm_preload.so
    libxahead.so
)

case " $LD_PRELOAD " in
    (*[:\ ]"$sofiles"[:\ ]*) ;;
    (*) export LD_PRELOAD="${LD_PRELOAD:+$LD_PRELOAD } ${sofiles[@]}"
        ;;
esac

export WINEDLLOVERRIDES="mscoree,mshtml="
export WINEDEBUG="warn-all,err+all"

if [ $# -gt 0 ] ; then
    path="/opt/World of Warcraft 3.3.5a/$1/Wow.exe"
else
    path="/opt/World of Warcraft 3.3.5a/Wow.exe"
fi

for i in $(seq 1 ${2:-1}); do
    wine "$path" &
    sleep 0.4
done
