#!/bin/bash

d=0
while [ -e /tmp/.X$d-lock ] ; do
    d=$(($d + 1))
done

display=":$d"

WINEPREFIX="/tmp/.winebot-$d"

if [ ! -d "$WINEPREFIX" ] ; then
    install -d "$WINEPREFIX"
    install -d "$WINEPREFIX/drive_c"
    ln -s "$HOME/.wine/drive_c/windows"             "$WINEPREFIX/drive_c/"
    ln -s "$HOME/.wine/drive_c/Program Files"       "$WINEPREFIX/drive_c/"
    ln -s "$HOME/.wine/drive_c/Program Files (x86)" "$WINEPREFIX/drive_c/"
fi

export WINEPREFIX
unset d

shcmd="cd $HOME/src/wotlk/src/WoW/Wotlk/"

{ xinit /bin/sh -c "vglrun wew $@ > /dev/null 2>&1" \
    -- /usr/bin/Xephyr $display -screen 622x513 -softCursor > /dev/null 2>&1 ; \
    exit ; } &

{ cd "$HOME/src/wotlk/src/WoW/Wotlk/" ; \
    export DISPLAY=$display ; \
    export PS1="\[\e[1m\](\[\e[0m\]xebot \[\e[1;32m\]$display \[\e[34m\]\W\[\e[37m\])\[\e[0m\]\$ " ; \
    bash --norc ; }

